"""Remove wallet add refund tracking

Revision ID: dfdee4af91b7
Revises: 71eed31947aa
Create Date: 2026-01-29 17:22:49.635850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdee4af91b7'
down_revision: Union[str, Sequence[str], None] = '71eed31947aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import sqlmodel

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('is_refunded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('payments', sa.Column('refund_id', sa.String(), nullable=True))
    
    # DATA CLEANUP: Link existing payments to vehicles via bookings
    op.execute("""
        UPDATE payments p
        SET vehicle_id = b.vehicle_id
        FROM booking b
        WHERE p.booking_id = b.id
    """)

    # If some payments don't have bookings, we might need a default vehicle or just delete them.
    # For now, let's just make it NOT NULL after update.
    op.alter_column('payments', 'vehicle_id', nullable=False)

    op.create_index(op.f('ix_payments_vehicle_id'), 'payments', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_column('user', 'wallet_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_balance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_vehicle_id'), table_name='payments')
    op.drop_column('payments', 'refund_id')
    op.drop_column('payments', 'is_refunded')
    op.drop_column('payments', 'vehicle_id')
    # ### end Alembic commands ###
